[programs.localnet]
solbond = "GGoMTmrJtapovtdjZLv1hdbgZeF4pj8ANWxRxewnZ35g"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/pouya/.config/solana/id.json"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register tests/**/*.ts"
# test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

