[provider]
cluster = "https://api.google.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "CNYbaeQEV1s3TwDXLYyEWCBxp1rC9u1To48WWKDBQzph"

[programs.devnet]
solbond = "CNYbaeQEV1s3TwDXLYyEWCBxp1rC9u1To48WWKDBQzph"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
