[provider]
cluster = "https://withered-twilight-frost.solana-devnet.quiknode.pro/43ea73628381d3d62b1edd54c1d3b5eb18737fef/"
wallet = "~/.config/solana/id.json"

[programs.localnet]

solbond = "FAFYPjvceW8PsAgbaxT84CizUM6zV7hosbhgiCm2fkng"

[programs.devnet]
solbond = "FAFYPjvceW8PsAgbaxT84CizUM6zV7hosbhgiCm2fkng"


[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/home/ahmet/.nvm/versions/node/v16.14.0/bin/node /home/ahmet/.nvm/versions/node/v16.14.0/bin/mocha -t 1000000 --require ts-node/register"
