[provider]
cluster = "https://api.google.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "2Wjm2Wpu4JsV1zv8yHgTEtJxCmGCTieUiPtisHimVBHi"

[programs.devnet]
solbond = "2Wjm2Wpu4JsV1zv8yHgTEtJxCmGCTieUiPtisHimVBHi"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/home/ahmet/.nvm/versions/node/v16.14.0/bin/node /home/ahmet/.nvm/versions/node/v16.14.0/bin/mocha -t 1000000 --require ts-node/register"
