[programs.localnet]
solbond = "6wMXJDkQGTykQq2Sf7rPit2qz7H5nsaw4iVKWNrAgd43"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/davidal/.config/solana/id.json"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register tests/**/*.ts"
# test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

