[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "EUBBaxNut3Z79MxGFTa4DsfUdAkdrwEP7b7Zc1W9Hj2H"

[programs.devnet]
solbond = "EUBBaxNut3Z79MxGFTa4DsfUdAkdrwEP7b7Zc1W9Hj2H"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
