[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "FAFYPjvceW8PsAgbaxT84CizUM6zV7hosbhgiCm2fkng"

[programs.devnet]
solbond = "FAFYPjvceW8PsAgbaxT84CizUM6zV7hosbhgiCm2fkng"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
