[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "Bqv9hG1f9e3V4w5BfQu6Sqf2Su8dH8Y7ZJcy7XyZyk4A"
amm = { address = "3f2yCuof5e1MpAC8RNgWVnQuSHpDjUHPGds6jQ1tRphY", idl = "./deps/invariant/target/idl/amm.json" }
staker = { address = "8uGzHXsuncH8aD9RFBYTHpV2eG3nD48FV1eyyghLDtfn", idl = "./deps/invariant/target/idl/staker.json" }

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "3f2yCuof5e1MpAC8RNgWVnQuSHpDjUHPGds6jQ1tRphY"
program = "./deps/invariant/target/deploy/amm.so"

[[test.genesis]]
address = "8uGzHXsuncH8aD9RFBYTHpV2eG3nD48FV1eyyghLDtfn"
program = "./deps/invariant/target/deploy/staker.so"

[scripts]
#test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register tests/**/*.ts"
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register tests/**/solbond-initialize-invariant-pools.ts"
# test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

