[provider]
cluster = "http://localhost:8899 "
wallet = "~/.config/solana/id.json"

[programs.localnet]

solbond = "ELkkgofct1n4bpFASAe9C27nWQEKkd7HYwoFq5hXT9XW"

[programs.devnet]
solbond = "ELkkgofct1n4bpFASAe9C27nWQEKkd7HYwoFq5hXT9XW"


[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
