[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "HbJv8zuZ48AaqShNrTCBM3H34i51Vj6q4RfAQfA2iQLN"

[programs.devnet]
solbond = "HbJv8zuZ48AaqShNrTCBM3H34i51Vj6q4RfAQfA2iQLN"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
