[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
solbond = "32jEsmA7t9yiX8MTr6TXmyKDC32rHBQ62ANciJA4g6wt"

[programs.devnet]
solbond = "32jEsmA7t9yiX8MTr6TXmyKDC32rHBQ62ANciJA4g6wt"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register"
