[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/amm", "programs/staker"]

[programs.localnet]
amm = "GpvoxwEz4AEPnWqhmD9DTfSQwUp3oQ5up71cWGVn2HsC"
staker = ""

[scripts]
#test = "ts-mocha -p ./tsconfig.json -t 1000000"
test = "/usr/local/bin/node /usr/local/bin/mocha -t 1000000 --require ts-node/register tests/**/*.ts"
